# React
FROM node:latest

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE jp_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV WATCHPACK_POLLING=true

RUN npm install -g create-react-app@latest
# frontend用フォルダ
WORKDIR /usr/frontend/serp
