FROM python:latest

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE jp_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade psycopg2-binary
RUN pip install --upgrade Flask
RUN pip install --upgrade flask_cors
RUN pip install --upgrade uwsgi
RUN pip install --upgrade openpyxl
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

CMD flask run --host=0.0.0.0 --port=5000 --debug 
