# バージョン固定
FROM postgres:16-bookworm

RUN apt-get update && \
    apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo

# PostgreSQL初期化時にロケールとエンコーディングを固定
ENV POSTGRES_INITDB_ARGS="--locale=ja_JP.UTF-8 --encoding=UTF8"

ENV POSTGRES_DB serp
ENV POSTGRES_USER serp
ENV POSTGRES_PASSWORD serp

# 初回起動時に照合順序バージョンを更新するSQLを実行
COPY init/init.sql /docker-entrypoint-initdb.d/