FROM postgres:latest

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE jp_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

ENV POSTGRES_DB serp
ENV POSTGRES_USER serp
ENV POSTGRES_PASSWORD serp

# Time ZoneAc
ENV TZ Asia/Tokyo
